### ISSUE TITLE
large backup size (due to storing backups in plugins folder instead of `ai1wm-backups`?)

### ISSUE THREAD

**Issue by dinesh-58** [shameemreza/all-in-one-wp-migration#2]
Noticed that this generates larger .wpress files compared to the unmodified plugin. When checking disk usage, it showed that .wpress files were being saved to `wp-content\plugins\all-in-one-wp-migration-master\storage` instead of `wp-content\ai1wm-backups`. I'm guessing these files are being included in the exported backup as well. Is this due to some modification or how the plugin worked in version 6.77? Or maybe I should've removed the `-master` from the zip file name before uploading?

**Comment by dinesh-58** [comment]
Update: Uninstalled both this and the unmodified plugin and reinstalled. Now, this saves the backup files to `wp-content\ai1wm-backups` but the file sizes are still larger (example: 1.25 GB now vs ~596 MB previously)

**Comment by shameemreza** [comment]
The modifications I added don't affect the file size or anything else. They just increased the limit for importing larger files.

However, this may be just how the plugin works. As a workaround, I suggest exporting using the latest version and importing using this old version.
